### ISSUE TITLE
Rewrite using generic math

### ISSUE THREAD

**Issue by LiphiTC** [Benjlet/IsEven#8]
.NET 7 introduced a new feature called generic math. Ig it's a good idea to use IBinaryInteger to make it to make it more abstract

**Comment by Benjlet** [comment]
It saddens me that .NET 7 has introduced `IsEvenInteger` and `IsOddInteger`, putting valuable third party even-checking packages in peril...

However, I have refactored the client accordingly to use `INumber` in a desperate bid to stay relevant - I hope this is everything you dreamt of.
